# Generated by Django 3.0 on 2020-04-13 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=50)),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile_photos')),
                ('background_photo', models.ImageField(blank=True, upload_to='back_photos')),
                ('short_description', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
