# Generated by Django 3.0 on 2020-04-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20200408_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='background_photo',
            field=models.ImageField(blank=True, upload_to='back_photos'),
        ),
        migrations.AlterField(
            model_name='company',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profile_photos'),
        ),
    ]
