# Generated by Django 3.0 on 2020-04-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20200408_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(default=4, max_length=50),
            preserve_default=False,
        ),
    ]
